import = [
  "/home/hen/.config/alacritty/colors.toml",
  "/home/hen/.config/alacritty/fonts.toml",
]
live_config_reload = true
#"windows.opacity" = 1.0

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_title = true
#gtk_theme_variant = "dark"
#history = 10000
#multiplier = 3
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 15
y = 15
